apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nais-example-v3-vars
  namespace: nais
  labels:
    team: nais
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
  liveness:
    path: /healthz
  readiness:
    path: /healthz
  envFrom:
    - configmap: example
