apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nais-example
spec:
  ttl: 1h
  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 21m
      memory: 32Mi
  liveness:
    path: /healthz
  readiness:
    path: /healthz
  #valkey:
    #- instance: cache
      #access: readwrite
