name: Deploy app (v3 with VARS)
on:
  push:
    branches: [main]
    paths:
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - "Dockerfile"
      - ".nais/app-v3-vars.yaml"
      - ".nais/vars-*.yaml"
      - ".github/workflows/deploy-app-v3-vars.yaml"

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v6
      - name: Build and push to GAR
        id: docker-build-push
        uses: nais/docker-build-push@v0
        with:
          team: nais
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
    name: Deploy to dev
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@deploy-v3
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app-v3-vars.yaml
          IMAGE: ${{ needs.build.outputs.image }}
          VARS: .nais/vars-dev.yaml

  deploy-prod:
    name: Deploy to prod
    needs: [build, deploy-dev]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@deploy-v3
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/app-v3-vars.yaml
          IMAGE: ${{ needs.build.outputs.image }}
          VARS: .nais/vars-prod.yaml
