name: Deploy app (v2 multi-resource)
on:
  push:
    branches: [main]
    paths:
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - "Dockerfile"
      - ".nais/app-v2-with-config.yaml"
      - ".github/workflows/deploy-app-v2-multi.yaml"

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v6
      - name: Build and push to GAR
        id: docker-build-push
        uses: nais/docker-build-push@v0
        with:
          team: nais
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/app-v2-with-config.yaml
          IMAGE: ${{ needs.build.outputs.image }}
