name: Deploy Nais resources
on:
  push:
    branches: [main]
    paths:
      - ".nais/**"
      - ".github/workflows/deploy-nais-resources.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: nais/setup@v1.0.0-next.7 # ratchet:exclude
        with:
          team: nais
      - name: Apply to dev-gcp
        run: |
          nais alpha apply .nais/config.yaml --environment dev-gcp
          nais alpha apply .nais/app.yaml --environment dev-gcp --wait
      - name: Apply to prod-gcp
        run: |
          nais alpha apply .nais/config.yaml --environment prod-gcp
          nais alpha apply .nais/app.yaml --environment prod-gcp --wait
